name: Interactive Mac SSH Terminal

on:
  workflow_dispatch:

jobs:
  ssh-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start Interactive SSH Session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
